name: Daily Market Update

on:
  schedule:
    - cron: '0 0 * * *' # Se lance tous les jours Ã  minuit
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/set-up-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas pyarrow

      - name: Run ETL
        run: python scripts/etl.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'izuku26'
          git config --global user.email 'idrissaabdallah26@gmail.com'
          git add data/market_data.parquet
          git commit -m "Auto-update market data" || exit 0
          git push